### ISSUE TITLE
internal IP only

### ISSUE THREAD

**Issue by umbm** [shizunge/endlessh-go#45]
Hi,

I installed the 3 containers and the router forwards external Port 22 to dockers POrt 2222.

After hours Grafana only shows the docker own IP 172.20.0.1 
How can I prevent logging this internal IP?

![Screenshot 2023-02-01 120955](https://user-images.githubusercontent.com/22610039/216027613-a234b5d7-8ed7-4d02-8ca8-2d570d6d07ca.png)

**Comment by umbm** [comment]
closed

problem is docker running at synology

**Comment by l33tlamer** [comment]
I have this exact same issue, but not running on Synology or any other kind of NAS. Its a rented VPS running plain Debian Bookworm with a public IPv4 assigned to eth0.

Docker is installed as usual (from official Docker apt repo), everything else is working fine. Its using the default bridge network.

However when i run endlessh-go as container with published ports for the SSH, all the incoming connections are logged as coming from the Docker container gateway (which technically is correct). But considering the purpose of this project, reporting internal IP´s is very pointless and of course is ignored with GeoIP etc.

The only way i found to make it "work" is to run the container with "network_mode: host" then it "sits" directly on the host network and incoming connections get reported with their actual public IP´s.

But using that mode introduces a lot of security issues, so its not really a fix to the problem. In addition, when enabling the metrics output for Prometheus, that port is then also open to the Docker host without any authentication. Its not possible to bind the metrics port only the localhost while also using host mode. Of course i can (and have) a firewall in front so the metrics port is not accessible from the outside, but this is still a problem.

Using a MACVLAN or IPVLAN Docker network also is not a solution because i cannot simply assign another public IPv4 to the container.

How are other people actually using this with a Docker setup? With a basic setup, i can either have useless IP´s reported, or i lower my security with network_mode host.

**Comment by Z0pyrus** [comment]
I had the same issue.
I solved it by redirecting all the traffic of endlessh-go into a socket and then mounting this socket into docker (while endlessh-go is running on the Host). There is a merge request that would make this very easy. https://github.com/shizunge/endlessh-go/pull/128
